### ISSUE TITLE
Why is Vite better than Parcel?

### ISSUE THREAD

**Issue by artginzburg** [KonradLinkowski/AntiCollision#5]
Regarding, #3, just wanted to know your thoughts about Vite's advantages. This stat shows that Vite is slower: https://github.com/devongovett/parcel-vs-vite-vs-turbopack-hmr (I did not check it). The things I like about Vite is that it's more modern, and it uses `pnpm` even in the docs.

**Comment by KonradLinkowski** [comment]
Hi @artginzburg  `parcel-bundler` is deprecated. There is a newer version of parcel, but seems like vite requires less configuration or I'm just used to it now
