### ISSUE TITLE
GML Port?

### ISSUE THREAD

**Issue by JesterOC3** [KonradLinkowski/AntiCollision#6]
Hi there,
I am looking to have this code ported.
( to GML ( GameMaker Language ) )

I had a look over the code, but without knowledge of how it works proper I'm unable to port it successfully.

**Any chance you could help?**

**Comment by KonradLinkowski** [comment]
Hi @JesterOC3 I don't remember how it works, but I think I just translated the original code from c++ to javascript https://github.com/johnBuffer/NoCol/blob/master/src/main.cpp
I think this code looks more straightforward in c++ so you can try
I'm pretty sure that every frame a center of mass of the entire system is calculated and then every particle get a velocity in that direction and that's it

**Comment by JesterOC3** [comment]
Thanks for the informative response. 

I had it ported to GML already, but it's good to know a bit more about what it's doing behind the scenes.
Have a good day.

**Comment by JesterOC3** [comment]
Ported to GML
